#!/bin/sh
# bspce - bspc extended
#
# After trying a lot of window managers before falling in love with `bspwm`, I
# realized that I really mostly used it in one of two ways: either I wanted
# *two* windows side by side or I wanted *one* window in fullscreen. Once I
# started using tablets, this observation gained importance, as simplicity is
# key for simultaneously accommodating both keys and touch gestures.
#
# Imagine a desk with a stack of papers. You're only ever working on one sheet;
# at most, you might hold two papers side by side. This inspired the following
# approach, for reducing the mental load. (Description to follow later).
#
# Assign appropriate shortcuts with <https://github.com/baskerville/sxhkd> and
# <https://git.sr.ht/~mil/lisgd>.
#
# This is an experiment for `bspwm`. If it works well, it would be nice to make
# a dedicated Wayland-based WM with better touch support --- hopefully
# something like `penrose` for Wayland will exist by then.

initialize(){
    trap clean EXIT
    bspc config external_rules_command $(realpath $0)
    bspc subscribe desktop_focus node_remove | while read e; do
        for desktop_id in $(bspc query -D -d '.!occupied'); do
            bspc desktop "${desktop_id}" --remove || :
        done
    done
}

finalize(){
    echo "Cleaning..." >&2
    bspc config external_rules_command off
    bspc node 'any.!window.leaf' --kill
}

# Remove all unused desktops and receptacles
# Usage: clean
clean(){
    for N in $(bspc query -N -n '.!window.leaf'); do
        bspc node $N --kill
    done
    for D in $(bspc query -D -d '.!occupied'); do
        bspc desktop "$D" --remove || :
    done
}

opposite(){
    [ "$1" = "prev" ] && echo next || echo prev
}

# Move window to previous or next
# Usage: move (prev|next)
move(){
    DIR="$1"
    bspc desktop --bubble "$DIR"
    bspc node --swap "@$(opposite $DIR):/"
}

# Merge the windows of this desktop with those of the next/prev one
# Usage: merge (next|prev)
merge(){
    DIR="$1"
    if [ "$DIR" = prev ]; then
        bspc config initial_polarity first_child
    else
        bspc config initial_polarity second_child
    fi
    bspc node "@$DIR:/" -n "@/"
    bspc desktop "$DIR" -r
}

# Make a desktop with a new one-letter name and return the name
new_desktop(){
    NAME="$(echo 'fjdkslaeiwovmcxqptybnz' \
        | tr -d "$(bspc query -D --names)" | head -c1)"
    bspc monitor -a "$NAME"
    echo $NAME
}


# Move a desktop relative to another
# Usage: insert DESKTOP_SEL [before|after] [DESKTOP_SEL]
insert(){
    SEL="$(bspc query -D --names -d $1)" || return 1
    REF="$(bspc query -D --names -d ${3:-focused})" || return 1
    [ "$SEL" = "$REF" ] && return 0
    [ "$2" = "before" ] && NEW="$SEL\n$REF" || NEW="$REF\n$SEL"
    bspc query -D --names | sed "/$SEL/d;s/$REF/$NEW/" | xargs bspc monitor -o
}

# Return without error only if the first desktop occurs after the second one in
# the desktop list
# Usage: successor DESKTOP_SEL [DESKTOP_SEL]
successor(){
    SEL="$(bspc query -D -d $1)" || return 1
    REF="$(bspc query -D -d ${2:-focused})" || return 1
    [ "$(bspc query -D | grep -m1 "^$SEL\|^$REF")" = "$SEL" ]
    return $?
}

# "Explode" the given desktop, giving each window its own desktop
# Usage: explode [DESKTOP_SEL]
explode(){
    D="${1:-focused}"
    for W in $(bspc query -N -d $D -n '.window.!floating' | tail -n+2); do
        DW="$(new_desktop)"
        insert "$DW" after focused
        bspc node "$W" -d "$DW"
    done
}

rule_command(){
    D="$(new_desktop)"
    if bspc query -N -n '@/1#focused.descendant_of' > /dev/null; then
        insert "$D" after focused > /dev/null
        bspc node "@$D:/" -i
        bspc node "@/2" --swap "@$D:/"
        echo node=@/2
    elif bspc query -N -n '@/2#focused.descendant_of' > /dev/null; then
        insert "$D" before focused > /dev/null
        bspc node "@$D:/" -i
        bspc node "@/1" --swap "@$D:/"
        echo node=@/1
    else # assume single window
        insert "$D" after focused > /dev/null
        echo desktop=$D follow=on
    fi
}


# If the argument matches any function we defined, execute it. Otherwise,
# assume
if [ "$(type $1)" = "$1 is a shell function" ]; then
    "$@"
    exit $?
elif [ ! -z "$1" ]; then
    rule_command "$@"
fi
