#!/bin/sh
# This script automatically cleans empty bspwm desktops

bspc subscribe desktop_focus node_remove node_transfer | while read e; do
    for desktop_id in $(bspc query -D -d '.!occupied.!focused'); do
        bspc desktop "${desktop_id}" --remove || :
    done
done
