#!/bin/bash
# Run this script in the background to make sure that `bspwm`s empty desktops
# get cleaned up.
set -euo pipefail

bspc subscribe desktop_focus | while read e; do
    for desktop_id in $(bspc query -D -d '.!occupied.!focused'); do
        bspc desktop "${desktop_id}" --remove
    done
done
