#!/bin/bash
# This script continuously changes the name of bspwm's desktops to reflect the
# number of client windows it contains
set -euo pipefail

function rename {
    for desktop_id in $@; do
        bspc desktop "${desktop_id}" --rename " $(bspc query -N -d "${desktop_id}" -n .leaf | wc -l
        )× " || :
    done
}

# Initial renaming
rename $(bspc query -D)

# ... and change desktop names as we move on
bspc subscribe desktop_add node_{add,remove,transfer} | while read -a e; do
    case "${e[0]}" in
        node_add|node_remove|desktop_add)
            rename "${e[2]}" ;;
        node_transfer)
            rename "${e[2]}" "${e[5]}" ;;
    esac
done
