#!/bin/bash
# This script makes sure that empty desktops get cleaned up.
set -euo pipefail

bspc subscribe desktop_focus | while read e; do
    for desktop_id in $(bspc query --desktops --desktop '.!occupied.!focused'); do
        bspc desktop "${desktop_id}" --remove
    done
done
