#!/bin/sh
# Keep presenting synonyms in a dmenu by querying freethesaurus.com
# Dependencies: bemenu htmlq findutils coreutils

DMENU="bemenu -i --no-exec"
while
    NEXT="$(echo -n "$NEXT" \
        | $DMENU \
        | tr ' ' '+' \
        | xargs -r -I{} curl --silent https://www.freethesaurus.com/{} \
        | htmlq --text 'a.tw' \
        | uniq)"
    test "$NEXT"
do :
done
