#!/bin/bash
# Menu that just keeps presenting synonyms until you can find the word that was
# at the tip of your tongue

while
    NEXT_WORD="$(\
        echo -n "$NEXT_WORD" | \
        dmenu -p "" $DMENU_ARGS | \
        xargs --no-run-if-empty thesaurus)"
    test "$NEXT_WORD"
do 
    :
done
