#!/usr/bin/env python3
"""
Select desktop apps using dmenu.
"""

import subprocess
from gi.repository import Gio  # type: ignore


def desc(app):
    return f"{app.get_display_name()} - {app.get_description()}\n"


p = subprocess.Popen(
    ["dmenu", "-p", "Applications", "-i", "-fn", "Inconsolata-14", "-l", "20"],
    universal_newlines=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)

assert p.stdin and p.stdout

with p.stdin:
    for app in Gio.AppInfo.get_all():
        p.stdin.write(desc(app))

if p.wait() == 0:
    selection = p.stdout.read()
    if selection.strip():
        for app in Gio.AppInfo.get_all():
            if selection == desc(app):
                app.launch()
                break
