#!/bin/bash
# Construct a dmenu with submenus using JSON. 
#
# Example:
# echo '[{"title":"hello","body":[{"title":"world","body":"echo test"}]}]' | dmenu-json

# Get menu JSON from command line arguments or stdin
JSON="$(cat "$@")"

# Keep going deeper until we can't
while 
    test "$JSON" && OPTIONS="$(echo "$JSON" | \
        jq --raw-output --exit-status '.[]?.title')"
do
    SELECT="$(echo "$OPTIONS" | \
        dmenu -p "Menu:" $DMENU_ARGS)"
    JSON="$(echo "$JSON" | \
        jq --arg s "$SELECT" '.[] | select(.title==$s) | .body // empty')"
done

# Feed whatever is left to the shell
echo "$JSON" | jq --raw-output '.' | sh

