#!/bin/bash
# System menu using dmenu

declare -a NAMES
declare -A COMMANDS
function cmd {
    NAMES+=("$1"); COMMANDS["$1"]="$2"
}

cmd "lock" "i3lock -c 000000 --ignore-empty-password"
cmd "audio" "pavucontrol"
cmd "display" "arandr"
cmd "printer" "system-config-printer"
cmd "log out" "bspc quit"
cmd "reboot" "systemctl restart"
cmd "shutdown" "systemctl poweroff"

key=$(for k in "${NAMES[@]}"; do echo "$k"; done | dmenu -p 'System:')
if [ ! -z "$key" ]; then
    sh <<< "${COMMANDS[$key]}"
fi

