#!/bin/bash
# Query for confirmation through dmenu.

PROMPT="Are you sure? [y/N]"

case "$1" in
    -p|--prompt)
        PROMPT="$2"
        shift 2
        ;;
esac

ANSWER=$(dmenu $DMENU_ARGS -p "$PROMPT" < /dev/null)
case "$ANSWER" in
    [yY][eE][sS]|[yY])
        exec "$@"
        ;;
    *)
        exit 1
        ;;
esac

