#!/bin/bash
#
# The only thing I ever do with my music player is listen to albums, preferably
# from start to finish. I was frustrated with most music player interfaces as
# they were sluggish and hard to subject to my will. I wrote this simple script 
# that uses dmenu, playerctl and standard UNIX tools to control mpv through IPC
# and MPRIS.
#
# Dependencies: 
#       dmenu, mpv, mpv-mpris, playerctl, xdg-dirs, socat, find, shuf, sort, sed
#
#   sudo apt install dbus-x11


MUSIC="$(xdg-user-dir MUSIC)"
CACHE="$HOME/.cache/mpvcache"
SOCKET="/tmp/mpvsocket"
PLAYLIST="/tmp/mpvplaylist"

# Test if an instance of mpv is already listening. If not, start one.
function initialise {
    test -S "$SOCKET" && socat /dev/null "$SOCKET" &> /dev/null
    if [ $? != 0 ]; then
        echo "Starting mpv at $SOCKET..." >&2
        mpv --idle --no-terminal --no-audio-display --input-ipc-server="$SOCKET" &
    fi
}

# Update the music database if it has changed.
function update-db {
    if [ ! -f "$CACHE" -o "$MUSIC" -nt "$CACHE" ]; then
        echo 'Caching music database...' >&2 
        find -L "$MUSIC" -type d -links 2 \
                | sed -n "s|^$MUSIC/||p" \
                | sort \
                > $CACHE
    fi
}

# Play all audio files in a directory.
function play {
    if [ -d "$1" ]; then
        find "$1" -regex '.*\.\(mp3\|webm\|m4a\|flac\|ogg\|wav\)' \
            | sort > "$PLAYLIST"
        echo '{"command":["loadlist","'"$PLAYLIST"'","replace"]}' \
            | socat - "$SOCKET" >&2
        playerctl --player=mpv pause
        playerctl --player=mpv play
    else
        echo "Album at '$1' not found." >&2
    fi
}

case "$1" in
    -i|--initialise)
        initialise
        ;;
    "")
        update-db
        INPUT=$(shuf "$CACHE" | dmenu -p "" -i)
	if [ "$INPUT" ]; then
		play "$MUSIC/$INPUT"
	fi 
        ;;
    -r|--random) 
        update-db
        play "$MUSIC/$(shuf -n1 $CACHE)"
        ;;
    -m|--monitor)
        sleep 1; playerctl --follow --format '{{status}}  {{title}} ({{artist}} - {{album}})' metadata \
            | sed --unbuffered 's/^Playing//g;s/^Paused//;s/^Stopped.*//g'
        ;;
    -t|--toggle)
        playerctl --player=mpv play-pause
        ;;
    -q|--quit)
        playerctl --player=mpv stop
        ;;
esac
