#!/bin/sh

FD="$(which fdfind || which fd)"

$FD . --base-directory $HOME/library books reference papers \
| shuf \
| dmenu -p Library -i $DMENU_OPTS \
| xargs --no-run-if-empty -I{} mupdf "$HOME/library/"{}
