#!/bin/bash
# System menu using dmenu

CMDS='
{   "lock": "i3lock -c 000000 --ignore-empty-password"
,   "audio": "pavucontrol"
,   "display": "arandr"
,   "printer": "system-config-printer"
,   "log out": "i3-msg exit"
,   "reboot": "systemctl restart"
,   "shutdown": "systemctl poweroff"
}'

CHOICE="$(jq -r 'to_entries[] | .key' <<<${CMDS} | dmenu -p 'System:' $DMENU_ARGS)"
jq -r --exit-status --arg s "${CHOICE}" '.[$s]' <<<${CMDS} | sh 2> /dev/null
