#!/bin/bash
# System menu using dmenu

declare -a NAMES
declare -A COMMANDS
function cmd {
    NAMES+=("$1"); COMMANDS["$1"]="$2"
}

cmd "  lock" "i3lock -c 000000 --ignore-empty-password"
cmd "蓼  audio" "pavucontrol"
cmd "  display" "arandr"
cmd "朗  printer" "system-config-printer"
cmd "  log out" "bspc quit"
cmd "勒  reload" "pkill -USR1 -x sxhkd; bspc wm -r; polybar-msg cmd restart"
cmd "勒  reboot" "systemctl reboot"
cmd "⏼  shutdown" "systemctl poweroff"

key=$(for k in "${NAMES[@]}"; do echo "$k"; done | dmenu -p '' ${DMENU_ARGS})
if [ ! -z "$key" ]; then
    sh <<< "${COMMANDS[$key]}"
fi

