#!/bin/bash
# Open a file. `xdg-open` is too much hassle.

f="${1}"

# Test if we are running within an X session; if so, fork the process and
# redirect the output so the terminal emulator is still available for other
# tasks.
function gui {
    if xset q &>/dev/null; then
        ("$@" > /dev/null 2>&1 ) &
    else
        "$@"
    fi
}


case $(file --dereference --mime-type "$f" -b) in
    inode/directory)
        lf "$f"
        ;;
    inode/x-empty) 
        nvim "$f" 
        ;;
    text/html)
        gui firefox "$f"
        ;;
    text/*) 
        nvim "$f"
        ;;
    video/*) 
        gui mpv --no-terminal "$f"
        # use --vo=gpu --gpu-context=drm if no X server
        ;;
    audio/midi)
        timidity "$f"
        ;;
    audio/*) 
        mpv --no-audio-display "$f"
        ;;
    image/*) 
        gui sxiv -a "$f" "$(dirname "$f")"
        ;;
    application/epub+zip) 
        gui mupdf -r 70 "$f" &
        #epr "$f" within terminal
        ;;
    application/zip)
        EXT="$(echo "${f##*.}" | tr '[:upper:]' '[:lower:]')"
        case $EXT in
            cbz)
                gui zathura "$f" &
                ;;
            *)
                gui xdg-open "$f"
                ;;
        esac
        ;;
    application/x-rar)
        EXT="$(echo "${f##*.}" | tr '[:upper:]' '[:lower:]')"
        case $EXT in
            cbr)
                gui zathura "$f" &
                ;;
            *)
                xdg-open "$f"
                ;;
        esac
        ;;
    application/pdf) 
        gui zathura "$f" &
        ;;
    application/x-wii-rom)
        gui dolphin-emu --exec="$f" &
        ;;
    application/x-gba-rom|application/x-gameboy-rom)
        gui retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/mgba_libretro.so" "$f"
        ;;
    application/x-n64-rom)
        gui retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/mupen64plus_libretro.so" "$f"
        ;;
    application/x-nintendo-ds-rom)
        gui retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/desmume_libretro.so" "$f"
        ;;
    application/x-nes-rom)
        gui retroarch \
            -L "/usr/lib/x86_64-linux-gnu/libretro/nestopia_libretro.so" "$f"
        ;;
    application/octet-stream)
        EXT="$(echo "${f##*.}" | tr '[:upper:]' '[:lower:]')"
        case $EXT in
            zim)
                gui kiwix-desktop "$f"
            ;;
            sfc|smc)
                gui retroarch -L "/usr/lib/x86_64-linux-gnu/libretro/bsnes_mercury_balanced.so" "$f"
            ;;
            mts)
                mpv "$f"
            ;;
        esac
        ;;
    message/rfc822)
        gui kmail --view "$f" &
        ;;
    *)
        xdg-open "$f"
        ;;
esac

