#!/bin/bash
# Make a new file based on a template.
#
# Usage example:
#   file-new this-is-a-document.md some-image.svg

TEMPLATE_DIR="$(xdg-user-dir TEMPLATES)"

for F in "${@}"; do
    if [ -e "$F" ]; then
        echo "File \"$F\" already exists." >&2 
        exit 1
    else
        EXTENSION="$(echo "${F##*.}" | tr '[:upper:]' '[:lower:]')"

        # File types for which there is a template
        TEMPLATE="$(find -L "$TEMPLATE_DIR" \
            -maxdepth 1 -type f -name '*'".$EXTENSION" -print -quit | grep .)"
        if [ "$?" -eq 0 ]; then
            cp "$TEMPLATE" "$F"
            exit 0
        fi

        # File types for which we can generate a template 
        TEMPLATE="$(find -L "$TEMPLATE_DIR/exec" \
            -maxdepth 1 -type f -name '*'".$EXTENSION" -print -quit | grep .)"
        if [ "$?" -eq 0 ]; then
            "$TEMPLATE" "$F" > "$F"
            exit 0
        fi

        # Otherwise, just make an empty file
        touch "$F"
    fi
done

