#!/bin/sh
# A simple dmenu interface to the password manager `pass`. Selects a password,
# then copies it to the clipboard.

[ -z $PASSWORD_STORE_DIR ] && PASSWORD_STORE_DIR="$HOME/.password-store"

fdfind . -e gpg --base-directory "$PASSWORD_STORE_DIR/" \
| sed 's/.gpg$//' \
| sort \
| fzf --exact \
| xargs --no-run-if-empty pass show --clip
