#!/bin/sh

echo 'lock:i3lock -c 000000 --ignore-empty-password
audio:pavucontrol
display:arandr
printer:system-config-printer
log out:bspc quit
reload:pkill -USR1 -x sxhkd; bspc wm -r; polybar-msg cmd restart
reboot:systemctl reboot
shutdown:systemctl poweroff' \
| fzf --exact --with-nth 1 -d: \
| cut -d: -f2- \
| sh
