#!/bin/bash
# `mom`
# Execute an operation in the current directory, and if it fails, try again in
# the parent directory. I use it to call `make` from any subdirectory.
# It would be nice to also automatically add $(realpath $PWD --relative-to
# $ORIGINAL) to the Makefile targets, but then I'd have to differentiate
# between phony targets and real ones.

# ORIGINAL="$PWD"
if [ $# -eq 0 ]; then
    echo "No operation given." 1>&2
else
    while : ; do
        "$@" && exit
        CHILD="$PWD"; cd ..
        [ "$CHILD" = "$PWD" ] && break
    done
fi

echo "Failed to execute \"$@\" in any directory." 1>&2
