#!/bin/bash
# Find Markdown files based on their `pandoc` metadata blocks. Use `jq`
# syntax to find them. 
#
# Example:
#   pdfind '.author=="nsv"'

if [ ! -z "${@:-}" ]; then
    # I am using `yj` to read the pandoc metadata, because I reckon it's faster
    # than using `pandoc` with `pandoc-metadata` template
    find . -iname '*.md' -o -iname '*.markdown' | while read LINE; do
        if yj < "$LINE" | jq -e "$@" > /dev/null; then
            echo "$LINE"
        fi
    done
fi
