#!/bin/bash
# photo-scanner
#
# I use this to scan and then automatically separate, crop and de-rotate analog
# pictures. The script is inspired by `fmwconcepts.com/imagemagick/multicrop`,
# but written from scratch as the aforementioned is not libre.
set -euo pipefail
IFS=$'\n\t'

# Make a temporary directory for this run, and make sure it will get deleted
TMP=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXX")
function finalize {
    rm -rf "${TMP}"
}
trap finalize EXIT

INPUT="${TMP}/scan.pnm"
LOC="${TMP}/local-mask.mpc"
GLOB="${TMP}/global-mask.mpc"
DPI=300 # DPI resolution
FUZZ=10 # How exact are we with color
GRID=6 # How many grid points are we testing in either dimension?
TITLE="${1}" # What is the title of the output file?

if [ -z "${TITLE}" ]; then
    echo "No title given!"
    exit 1
fi

# Scan the original image
echo "Starting up scanner..."
scanimage \
    --progress \
    --resolution ${DPI} \
    -l 2 -t 2 -x 214 -y 296 \
    --format pnm > ${INPUT}
echo "Scan finished. Now cropping and de-rotating..."

# Make a mask such that the background of the scan is transparent and
# everything else is plain red
convert ${INPUT} -fuzz ${FUZZ}% \
    -fill none -draw "matte 0,0 floodfill" \
    -fill red +opaque none \
    ${GLOB}

# Now we try to find each individual photo by looping over a grid
N=1
for((I=1; I < ${GRID}; I++)); do for((J=1; J < ${GRID}; J++)); do

    X=$(convert ${GLOB} -format "%[fx:round(${I}/${GRID}*w)]" info:)
    Y=$(convert ${GLOB} -format "%[fx:round(${J}/${GRID}*h)]" info:)

    # If the color at this position is not transparent, we found a picture!
    if [ $(convert ${GLOB} -format "%[fx:u.p{$X,$Y}==none]" info:) -eq 0 ]; then
        OUTPUT="${TITLE}-${N}.jpg"

        if [ -f "$OUTPUT" ]; then
            echo "File \"${OUTPUT}\" already exists!"
            exit 1
        fi
       
        # Create local mask by making only the current region opaque
        convert ${GLOB} -fuzz ${FUZZ}% \
            -fill white -draw "color $X,$Y floodfill" \
            +transparent white \
            ${LOC}

        # Compose the local mask with the scan, then trim and de-rotate
        echo "Writing ${OUTPUT}..."
        convert ${INPUT} -alpha on \
            ${LOC} -compose Dst_In -composite \
            -background white -alpha remove \
            -trim -deskew 40% -trim +repage \
            ${OUTPUT}

        # Remove current region from the global mask so that it won't be found again
        convert ${GLOB} -fuzz ${FUZZ}% \
            -fill none -draw "matte $X,$Y floodfill" ${GLOB}

        N=$(($N+1))
    fi
done
done
