#!/bin/bash
# This quick script provides a way to print paper-efficient, double-sided
# booklets from PDFs on my cheap printer.
# 
# Since I put them in an A5 organizer, my first idea was to print pages
# 4+1,8+5..., then print pages 2+3,6+7... on the other sides, but selecting
# that way is too much hassle --- easier to just use pdfbook.

set -euo pipefail
IFS=$'\n\t'

PRINTER="HL1110"
GS_ARGS="-q -dNOPAUSE \
    -dBATCH -sDEVICE=pdfwrite -dSAFER \
    -dCompatibilityLevel=1.3 -dPDFSETTINGS=/printer"

# This crops the whitespace away
pdfcrop --margins 20 "$1" /tmp/book1.pdf

# This scales it back to A4 size
gs $GS_ARGS \
    -dFIXEDMEDIA \
    -dPDFFitPage \
    -sPAPERSIZE=a4 \
    -sOutputFile="/tmp/book2.pdf" \
    -f "/tmp/book1.pdf"

# Makes it a booklet
pdfbook --delta '2cm 0cm' --outfile "/tmp/book3.pdf" /tmp/book2.pdf

# Select even pages to print
gs $GS_ARGS \
    -sPageList=odd \
    -sOutputFile="/tmp/book-odd.pdf" \
    -f "/tmp/book3.pdf"

gs $GS_ARGS \
    -sPageList=even \
    -sOutputFile="/tmp/book-even.pdf" \
    -f "/tmp/book3.pdf"

# Print
lp -d "$PRINTER" -orientation-requested=4 /tmp/book-odd.pdf

read -p "Flip the pages, then press enter to continue."

lp -d "$PRINTER" -o outputorder=reverse -o orientation-requested=4 /tmp/book-even.pdf

