#!/bin/bash
# Uses http://www.risacher.org/sunwait/ to calculate when the sun will rise and
# set. Hacky.

readarray -t COORDS < <(/usr/lib/geoclue-2.0/demos/where-am-i -t 2 | sed -n 's/.*itude:\s\+\(.*\)°/\1/p')

[ $COORDS ] || exit 1

LAT="${COORDS[0]}"
if (( $(bc <<< "$LAT > 0") )); then
    LAT="${LAT}N"
else
    LAT="$(bc <<< "$LAT * -1")S"
fi

LON="${COORDS[1]}"
if (( $(bc <<< "$LON > 0") )); then
    LON="${LON}W"
else
    LON="$(bc <<< "$LON * -1")E"
fi

sunwait -p $LAT $LON 
