#!/bin/bash
# Uses http://www.risacher.org/sunwait/ to calculate when the sun will rise and
# set. Would like to use geoclue2 instead to find lat/lon coords, but this will do.

curl -s https://ipapi.co/json \
    | jq -r \
        '[(.latitude  | if . > 0 then (.|tostring)+"N" else (.*-1|tostring)+"S" end)
         ,(.longitude | if . > 0 then (.|tostring)+"W" else (.*-1|tostring)+"E" end)] | .[]' \
    | xargs sunwait -p \
    | sed -n 's/\s*Sun rises \([0-9][0-9]\)\([0-9][0-9]\)[^0-9]*\([0-9][0-9]\)\([0-9][0-9]\).*/ \1:\2-\3:\4/p'
