#!/usr/bin/env python3
# Quick and dirty thesaurus using BeautifulSoup and TheFreeDictionary. Simply
# returns a newline-seperated list of words related to the one given.
# deps: python3-bs4 python3-lxml

import sys
import bs4
import urllib.request

word = "+".join(" ".join(sys.argv[1:]).split())

if word:
    url = "http://www.thefreedictionary.com/{}".format(word)

    try:
        page = urllib.request.urlopen(url, timeout=2)
    except urllib.error.HTTPError as e:
        sys.exit(1)

    soup = bs4.BeautifulSoup(page.read(), "lxml").find(id="Thesaurus")
    if soup:
        for x in soup.find_all(class_=["Syn","Rel"]):
            for y in x.find_all("a"):
                print(y.get_text())
